name: I would like to contribute!
description: Contributing a PR with what you are working on
labels: "contribution"
assignees: "TheM1ddleM1n"
body:
  - type: input
    attributes:
      label: What are you adding?
      description: Tell me a short description of what you plan to add or remove.
      placeholder: Streamlining performance and removing useless features.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Draft
      description: Please draft your idea here
